# Generated by Django 2.2.1 on 2019-05-28 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientsurvey',
            name='ref_token',
            field=models.UUIDField(null=True),
        ),
    ]
