# Generated by Django 2.2.1 on 2019-06-03 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_clientsurvey_ref_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientsurvey',
            name='child_age',
        ),
        migrations.RemoveField(
            model_name='clientsurvey',
            name='postgrad_start_age',
        ),
        migrations.RemoveField(
            model_name='clientsurvey',
            name='undergrad_start_age',
        ),
        migrations.CreateModel(
            name='ClientChild',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.PositiveSmallIntegerField()),
                ('undergrad_start_age', models.PositiveSmallIntegerField()),
                ('postgrad_start_age', models.PositiveSmallIntegerField()),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='survey.ClientSurvey')),
            ],
        ),
    ]
