# Generated by Django 2.2.1 on 2019-06-03 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0003_auto_20190603_0835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientchild',
            name='survey',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='survey.ClientSurvey'),
        ),
    ]
