# Generated by Django 2.2.1 on 2019-06-07 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0004_auto_20190603_0950'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientsurvey',
            name='email',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clientsurvey',
            name='first_name',
            field=models.CharField(max_length=75, null=True),
        ),
    ]
