# Generated by Django 2.2.1 on 2019-06-13 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0005_auto_20190607_0409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientchild',
            name='undergrad_start_age',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
