# Generated by Django 2.2.1 on 2019-06-13 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0006_auto_20190613_0919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientsurvey',
            name='annual_expenses',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='clientsurvey',
            name='annual_income',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='clientsurvey',
            name='assets',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='clientsurvey',
            name='existing_critical_illness_cover',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='clientsurvey',
            name='existing_life_insurance',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='clientsurvey',
            name='existing_medical_insurance',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='clientsurvey',
            name='existing_savings',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='clientsurvey',
            name='fees_as_per_today',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='clientsurvey',
            name='liabilities',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
    ]
